name: Label

on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  labelPR:
    name: add labels
    runs-on: ubuntu-latest
    steps:
      - name: Label PRs
        uses: tinkurlab/monorepo-pr-labeler-action
        env:
          BASE_DIRS: 'source|tools'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prefix: 'package: '
